name: MoonGoAdmin
description: A new Flutter project.

version: 2.2.0+2

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #DATA
  dio: ^3.0.10
  photo_view: ^0.9.2
  #encrypt
  encrypt: ^4.0.2
  clipboard: ^0.1.2+8
  # Bloc Pattern
  flutter_bloc: ^6.1.0
  # RxDart
  rxdart: ^0.24.1
  # Simplify Equality Comparisons
  equatable: ^1.2.5
  #Base Component
  platform_device_id: ^0.1.1
  device_info: ^0.4.2+8
  package_info: ^0.4.1
  url_launcher: ^5.5.0
  oktoast: ^2.3.2
  #Local Resources
  path_provider: ^1.6.11
  localstorage: ^3.0.2+5
  shared_preferences: ^0.5.12
  # This is a simple Service Locator for Dart and Flutter projects with some additional goodies highly inspired by Splat. It can be used instead of InheritedWidget or Provider to access objects e.g. from your UI.
  get_it: ^4.0.2
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.3.3
  sqflite: ^1.3.0
  flutter_datetime_picker: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: G 